### ISSUE TITLE
GPP-Skyblock Spamming Console

### ISSUE THREAD

**Issue by xKnightGamingx** [KaiKikuchi/GriefPreventionPlus-SkyBlock#14]
[00:36:56] [Server thread/WARN] [net.kaikk.mc.gpp.skyblock.GPPSkyBlock/]: [GPPSkyBlock] Task #2440 for GPPSkyBlock v1.3.7 generated an exception
java.lang.NullPointerException
    at org.bukkit.Location.getChunk(Location.java:73) ~[Location.class:1.7.10-1614.58]
    at net.kaikk.mc.gpp.skyblock.SpawnTeleportTask.run(SpawnTeleportTask.java:23) ~[?:?]
    at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) ~[CraftTask.class:1.7.10-1614.58]
    at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346) [CraftScheduler.class:1.7.10-1614.58]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:905) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]

This is spamming both my Skyfactory and Project ozone 2 servers and wont let anyone type /is spawn or anything

**Comment by KaiKikuchi** [comment]
Thanks for the report, this has been already fixed weeks ago, but I haven't pushed yet because there'll be a major update.
