### ISSUE TITLE
Issue resetting islands

### ISSUE THREAD

**Issue by xSINIQx** [KaiKikuchi/GriefPreventionPlus-SkyBlock#16]
Hey there,

I had some issues with resetting islands (error below), so i tried generating a new schematic, that worked but now players spawn next to the tree and fall directly into the void. is there some way to set the precise spawn point for new islands?

```
[01:45:11 INFO]: Cpt_SiN issued server command: /is reset
[01:45:14 INFO]: Cpt_SiN issued server command: /is reset
[01:45:14 INFO]: Generating Cpt_SiN island at [world, 2239,703~2367,831]
[01:45:14 INFO]: Cpt_SiN island regeneration complete.
[01:45:15 WARN]: java.util.zip.ZipException: too many length or distance symbols
[01:45:15 WARN]:        at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:164)
[01:45:15 WARN]:        at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:117)
[01:45:15 WARN]:        at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:122)
[01:45:15 WARN]:        at java.io.DataInputStream.readByte(DataInputStream.java:265)
[01:45:15 WARN]:        at com.sk89q.jnbt.NBTInputStream.readNamedTag(NBTInputStream.java:73)
[01:45:15 WARN]:        at com.sk89q.jnbt.NBTInputStream.readNamedTag(NBTInputStream.java:62)
[01:45:15 WARN]:        at com.sk89q.worldedit.extent.clipboard.io.SchematicReader.read(SchematicReader.java:75)
[01:45:15 WARN]:        at net.kaikk.mc.gpp.skyblock.ResetIslandTask.run(ResetIslandTask.java:93)
[01:45:15 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
[01:45:15 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346)
[01:45:15 WARN]:        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:905)
[01:45:15 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
[01:45:15 WARN]:        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
[01:45:15 WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
[01:45:15 WARN]:        at java.lang.Thread.run(Thread.java:745)
```

**Comment by KaiKikuchi** [comment]
The spawn point is the point when you do the "/schem save" command.

So be sure to select the area either with the wand (wooden axe) or //pos1 and //pos2, then move to the island spawn point before doing "/schem save"

**Comment by KaiKikuchi** [comment]
About the exception... I guess the schematic is too big..?

**Comment by xSINIQx** [comment]
Its the default schematic, which is included in the download.
I got it working now, probably is a basic worldedit thing i didnt know about :)
Thanks for the quick response!
Loving the plugins, good job!

**Comment by KaiKikuchi** [comment]
The default schematic is a vanilla schematic :). It usually doesn't work with modded stuff! Thank you for your support!
