### ISSUE TITLE
Error when creating islands

### ISSUE THREAD

**Issue by Eufranio** [KaiKikuchi/GriefPreventionPlus-SkyBlock#19]
I use the command **/is spawn**, and it throws an exception:
```
[02:36:38] [Server thread/INFO] [Minecraft/]: [GriefPreventionPlus] PotterCraft_ made a new claim (id 1) at [Sky, 2175,639~2431,895]
[02:36:38] [Server thread/INFO] [Minecraft/]: Generating PotterCraft_ island at [Sky, 2175,639~2431,895]
[02:36:39] [Server thread/INFO] [Minecraft/]: PotterCraft_ island regeneration complete.
[02:36:39] [Server thread/WARN] [/]: java.util.zip.ZipException: too many length or distance symbols
[02:36:39] [Server thread/WARN] [/]: 	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:164)
[02:36:39] [Server thread/WARN] [/]: 	at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:117)
[02:36:39] [Server thread/WARN] [/]: 	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:122)
[02:36:39] [Server thread/WARN] [/]: 	at java.io.DataInputStream.readByte(DataInputStream.java:265)
[02:36:39] [Server thread/WARN] [/]: 	at com.sk89q.jnbt.NBTInputStream.readNamedTag(NBTInputStream.java:73)
[02:36:39] [Server thread/WARN] [/]: 	at com.sk89q.jnbt.NBTInputStream.readNamedTag(NBTInputStream.java:62)
[02:36:39] [Server thread/WARN] [/]: 	at com.sk89q.worldedit.extent.clipboard.io.SchematicReader.read(SchematicReader.java:75)
[02:36:39] [Server thread/WARN] [/]: 	at net.kaikk.mc.gpp.skyblock.ResetIslandTask.run(ResetIslandTask.java:93)
[02:36:39] [Server thread/WARN] [/]: 	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
[02:36:39] [Server thread/WARN] [/]: 	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346)
[02:36:39] [Server thread/WARN] [/]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:905)
[02:36:39] [Server thread/WARN] [/]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
[02:36:39] [Server thread/WARN] [/]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
[02:36:39] [Server thread/WARN] [/]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
[02:36:39] [Server thread/WARN] [/]: 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Eufranio** [comment]
Sorry, duplicated issue.
